# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc41ad87a7c72bd5c611fa6f5f091b086ead187bfb96213d974219d7c8cd5e46d5496c47d29453a729d963c5b54a62ca0d683a3a5accdaa0e6069da0f8472bf6

test:
  secret_key_base: 151e07bba5f7cfbabe6d19d40ae6d9dba7871bfe5d504cf196ad3dfb8ead0b9adbc9d0c91760b32764055c809505860db16fdf576a9e97f060196bab897735ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
